import pytest

from gh_ml.readme_signals import README_EVIDENCE_VERSION, extract_readme_evidence


def test_paper_implementation_and_method_relation_are_detected_for_varied_ml_methods():
    samples = [
        """# DragGAN
        ## Overview
        We propose DragGAN, a GAN method for interactive image editing. Paper: [arXiv](https://arxiv.org/abs/2305.10973).
        Official implementation and code: https://github.com/example/draggan""",
        """# GPT-2
        We present an autoregressive language model. Paper: https://openai.com/research/better-language-models.
        This repository contains the official implementation and training code.""",
        """# I-JEPA
        We introduce a self-supervised vision transformer representation learning method. See the paper at https://arxiv.org/abs/2301.08243.
        Code for this paper is provided here.""",
        """# Diffusion model
        We propose a diffusion model for text-to-image generation. Paper: 2303.01234.
        Official code and pretrained model weights are included.""",
        """# Vision language model
        Our method trains a vision-language model with reinforcement learning.
        Code and implementation are provided.""",
    ]

    for readme in samples:
        result = extract_readme_evidence(readme)
        assert result["readme_evidence_version"] == README_EVIDENCE_VERSION
        assert {"ml-method-context", "method-contribution"} <= set(result["readme_signals"])
        assert "paper-code-relationship" in result["readme_signals"] if "paper" in readme.lower() else True
        assert result["readme_signals"] == sorted(result["readme_signals"])


def test_signals_do_not_join_unrelated_paper_and_generic_ai_mentions():
    result = extract_readme_evidence(
        """# Project
        See the paper at https://arxiv.org/abs/2301.01234.

        We use AI to organize personal finance records."""
    )

    assert "paper-reference" in result["readme_signals"]
    assert "ml-method-context" not in result["readme_signals"]
    assert "paper-code-relationship" not in result["readme_signals"]
    assert "method-contribution" not in result["readme_signals"]


def test_paraphrased_live_readmes_preserve_html_and_local_relations():
    draggan = extract_readme_evidence(
        """<p>Interactive editing of images generated by generative adversarial networks.
        Published in SIGGRAPH; <a href="https://arxiv.org/abs/2305.10973">paper</a>.</p>
        <p>Use the GUI to manipulate GAN-generated images.</p>"""
    )
    assert {"paper-reference", "ml-method-context"} <= set(draggan["readme_signals"])
    # That descriptive paragraph does not claim this repository is the paper's code.
    assert "paper-code-relationship" not in draggan["readme_signals"]

    animatediff = extract_readme_evidence(
        """<p>Official implementation for our arXiv paper. A plug-in module that
        transforms community text-to-image models into animation generators.</p>"""
    )
    assert {
        "paper-reference",
        "paper-code-relationship",
        "official-implementation-claim",
        "ml-method-context",
        "method-contribution",
    } <= set(animatediff["readme_signals"])

    ijepa = extract_readme_evidence(
        """The official PyTorch codebase for a joint-embedding predictive architecture,
        published at CVPR and available as a preprint at https://arxiv.org/abs/2301.08243."""
    )
    assert {
        "paper-reference",
        "paper-code-relationship",
        "official-implementation-claim",
        "ml-method-context",
    } <= set(ijepa["readme_signals"])

    gpt2 = extract_readme_evidence(
        "Code and models for the paper Language Models are Unsupervised Multitask Learners; "
        "this repository provides GPT-2 language models."
    )
    assert {"paper-reference", "paper-code-relationship", "ml-method-context"} <= set(gpt2["readme_signals"])
    # The README presents a release and use of an existing model, not a novelty claim.
    assert "method-contribution" not in gpt2["readme_signals"]


def test_pytorch_needs_architecture_or_method_context_and_module_creation_is_detected():
    assert "ml-method-context" not in extract_readme_evidence("PyTorch utilities and examples.")["readme_signals"]
    result = extract_readme_evidence("We design a training pipeline for Stable Diffusion.")
    assert {"ml-method-context", "method-contribution"} <= set(result["readme_signals"])


@pytest.mark.parametrize(
    "readme",
    [
        """# Zipline
        Documentation for the Zipline backtesting library. Use the API to run trading simulations.""",
        """# Jane Doe
        Researcher interested in machine learning, transformers, and computer vision.
        These are my notes and links to projects.""",
        """# Machine Learning Course
        Lecture notes and assignments for a deep learning course. We study transformers.""",
        """# Awesome ML
        A survey and reading list of machine learning, diffusion, and reinforcement learning papers.""",
        """# Reproduction
        A faithful reproduction of the paper's transformer model and results. Code is provided.""",
    ],
)
def test_course_profile_lists_and_reproductions_are_not_positive_contributions(readme):
    result = extract_readme_evidence(readme)
    assert "method-contribution" not in result["readme_signals"]
    assert "paper-code-relationship" not in result["readme_signals"]


def test_course_list_and_reproduction_cues_are_explicit():
    assert "course-cue" in extract_readme_evidence("A deep learning course.")["readme_signals"]
    assert "survey-cue" in extract_readme_evidence("A survey of transformers.")["readme_signals"]
    assert "reproduction-cue" in extract_readme_evidence("Faithful reproduction of results.")["readme_signals"]


def test_dataset_only_readme_gets_negative_cue():
    result = extract_readme_evidence("# Dataset\nA benchmark dataset and corpus for evaluation.")
    assert "dataset-only-cue" in result["readme_signals"]


def test_sections_are_fixed_enums_and_no_readme_text_is_returned():
    readme = """# Strange private project name
    ## Method
    We propose a transformer.
    ## Unrecognized custom heading
    Confidential text should not appear in the result."""
    result = extract_readme_evidence(readme)

    assert result["readme_sections"] == ["method", "other"]
    assert set(result) == {"readme_evidence_version", "readme_signals", "readme_sections"}
    assert "Confidential" not in repr(result)
    assert "Strange private project name" not in repr(result)


@pytest.mark.parametrize("value", [None, 12, b"README"])
def test_non_string_input_is_rejected(value):
    with pytest.raises(TypeError):
        extract_readme_evidence(value)


def test_markdown_code_is_ignored_and_input_is_bounded():
    result = extract_readme_evidence("```python\nWe propose a transformer.\n```\nDocs only." + "x" * 300_000)
    assert "method-contribution" not in result["readme_signals"]
